mkoctfile --mex ...												
    -I./Eigen ...
    -I./libigl/include ...
    -I/usr/include -I. ...
<<<<<<< HEAD
	-Wno-deprecated-declarations -std=c++11 ...
=======
    -I./boost ...
	-Wno-deprecated-declarations -Wno-ignored-attributes ...
	-std=c++11 ...
>>>>>>> cpp-module
	HierarchicalSmoothOctave.cpp libhsmooth.a
