mkoctfile --mex ...												
    -I./Eigen ...
    -I./libigl/include ...
    -I/usr/include -I. ...
    -I./boost ...
	-Wno-deprecated-declarations -Wno-ignored-attributes ...
	-std=c++11 ...
	HierarchicalSmoothOctave.cpp libhsmooth.a
